### ISSUE TITLE
BREAK EVEN by: Hilary Masland, Adrian Wyatt and Casey Gil 

### ISSUE THREAD

**Issue by hilarymasland** [ga-dc/wdi8-project3-gallery#10]
Link to repo: https://github.com/Wyatt23/break_even
Link to deployed app: https://break-even.herokuapp.com/#/

Things you'd like specific feedback on:
- A better way to populate and compare variables in angular across two different models.
- If we continue to progress - we're not sure what the differences are between controllers and models and when to use each one.
- How to store click functions in angular to a database

**Comment by joe-gz** [comment]
Really nice job here guys! I know this was a tough one, but I think there was a lot that came together well.  I'd definitely encourage you to keep working to get full CRUD set up, as right now there is just the Read for the most part.  You backend looks like it's really close to being ready to go with everything else!
I've left some in line comments for you (see below PR), and we will sit down for an in person feedback session later when I can answer any other questions.  

There is also a full feedback.md file with the actual rubric for you to check out too.

https://github.com/Wyatt23/break_even/pull/18/files
