### ISSUE TITLE
Where is my stuff

### ISSUE THREAD

**Issue by ghost** [ga-dc/wdi8-project3-gallery#13]

**Comment by ghost** [comment]
See readme for user stories

Members: Bipin, Kaira, Kim
we had repo issue cause Git was down so we have 2 repos

Link to Trello: https://trello.com/b/cVsERugY/ga-project-3
Link to repo 1: https://github.com/Bneupane/whereismystuff
link to repo 2: https://github.com/Bneupane/lostandfound
Link to Heroku: https://whereismystuff.herokuapp.com/#/

Need feedback on: 
1. when person who finds an item and reports it we want to be able to send a silent email to the owner saying that someone found their item.
2. when the person who finds an item puts in the barcode we want to be able to show who it belongs to.

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/Bneupane/whereismystuff/pull/21)
