### ISSUE TITLE
ZoosnapZ (Christine, Charles, Brendan)

### ISSUE THREAD

**Issue by christine-sm** [ga-dc/wdi8-project3-gallery#4]
Github: https://github.com/cmmovius/zoosnapz

Heroku: http://zoosnapz.herokuapp.com/zoos#/1

**Comment by beckybeauchamp1** [comment]
Hi Christine, Charles, and Brendan,

Awesome job on Project 3! Here is a link to my PR with comments, changes, and the evaluation file. https://github.com/cmmovius/zoosnapz/pull/37 

Please let me know if you have any further comments! :+1:
