### ISSUE TITLE
iHaveToGo (Max, Melissa, Maureen, Jeff)

### ISSUE THREAD

**Issue by jeffreyeaton76** [ga-dc/wdi8-project3-gallery#5]
An app for rating publicly accessible toilets.

GitHub: https://github.com/jeffreyeaton76/ihavetogo

Heroku: https://jeffreyeaton76-ihavetogo.herokuapp.com/

**Comment by RobertAKARobin** [comment]
# Project 3 Evaluation

[Inline code comments](https://github.com/jeffreyeaton76/ihavetogo/pull/38)

## Back-end Technology

**2: Performing**

> Includes 2 models

## Front-end Technology

**2: Performing**

> Front-end makes appropriate use of Angular controllers and states with ui-router. Includes 1 custom directive

## Code Quality

**2: Performing**

> Code is well-formatted, well-named, and contains few style / quality issues

## Deployment and Functionality

**2: Performing**

> Application contains no major errors, is deployed correctly, and contains a custom Heroku app name appropriate for the app.

## Planning / Process / Submission

**3: Excelling**

> Submission includes everything in previous category, as well as evidence of proper teamwork, such as feature branching, code review, github issue / user story tracking, and justification of technical decisions.

## Comments

Great job, guys! And obligatory "holy cow" to Maureen -- you get a thousand bonus points for creativity.

This is a _really cool_ app. I strongly encourage you guys to continue to work on this. Even if it's just for the novelty value, this thing would attract a lot of attention!

My only beefs were some code formatting issues which indicate HTML was invalid, and also some general DRYness issues: nothing significant enough to deduct points, but something to be aware of.
