### ISSUE TITLE
Viva la Vegan  - Team MWA (Straight Outta D.C.)

### ISSUE THREAD

**Issue by winishahines** [ga-dc/wdi8-project3-gallery#6]
Link to repo: https://github.com/MattLeeStevens/vivalavegan
Link to deployed app: https://vivalavegan.herokuapp.com

Things you'd like specific feedback on: 
Winnie - Best approach for adding foods to restaurants
Anissa - Best approach for adding reviews/comments
Matt - How to fix restaurant show page refresh

**Comment by amaseda** [comment]
Project evaluation: https://github.com/MattLeeStevens/vivalavegan/pull/61
