### ISSUE TITLE
iCare Volunteer Project --Team FAB (Farishta Haider, Alexa Klein, Brittany Branso)

### ISSUE THREAD

**Issue by aklein916** [ga-dc/wdi8-project3-gallery#8]
Link to repo: https://github.com/aklein916/iCare-Volunteer-Project
Link to deployed app: https://icare-volunteer-app.herokuapp.com/

Things you'd like specific feedback on:
Saving the new story from the form page when you press submit. Having the application show the data that we select in the dropdown on the first page.

**Comment by aklein916** [comment]
this is a link to the repo we were working from at the beginning of the first day. We decided to scrap it and start over, but it shows our work from Friday. 

https://github.com/LaFrish/Volunteer-Project

**Comment by beckybeauchamp1** [comment]
Hi all!

Good job on Project 3! Great job working through your challenges during Project week and creating a two model rails/angular application! Your design and interface looks great as well :)

Here is a link to my PR with further feedback : https://github.com/aklein916/iCare-Volunteer-Project/pull/66/files

Please let me know if you have any more questions :+1:
